import type { Metadata, Viewport } from "next";
import { Montserrat, Quicksand } from "next/font/google";
import "./globals.css";

// "Joyride" type pairing: Montserrat for confident headlines, Quicksand for friendly body/UI.
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["600", "700", "800"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const TITLE = "dascar — find your next car without the tab chaos";
const DESCRIPTION =
  "Answer a few quick questions and dascar searches real listings across dealers and private sellers, ranks them by value, and flags the lemons before you fall for one.";

// metadataBase + OG/Twitter so shared links render a proper preview card.
// The share image is generated by app/opengraph-image.tsx and auto-wired by Next.
export const metadata: Metadata = {
  metadataBase: new URL("https://dascar.xyz"),
  title: TITLE,
  description: DESCRIPTION,
  applicationName: "dascar",
  keywords: ["used cars", "car search", "car reliability", "NHTSA recalls", "car buying", "AutoTempest alternative"],
  openGraph: {
    type: "website",
    url: "https://dascar.xyz",
    siteName: "dascar",
    title: TITLE,
    description: DESCRIPTION,
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
};

export const viewport: Viewport = {
  themeColor: "#10363e",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${quicksand.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
